### ISSUE TITLE
Typing a colon (:) or period (.) produces multiple characters and lag spike

### ISSUE THREAD

**Issue by bryantbj** [bung87/vscode-rails#9]
# Issue
When working in `.rb` files, typing a `.`, as you would to access an object's method or attribute, multiple `.` characters are occasionally typed and a small lag spike occurs. The same thing happens when typing `:`, as you would in a hash argument. I've **only** noticed it happen when passing a hash as an argument to a method. The `:` lag spike seems to be much greater than the `.` spike. I feel a little ridiculous typing all this out, but these are simply my findings.

# Workaround
I disabled my VS Code extensions one-by-one, reloaded after each, and tested. Once I disabled `vscode-rails`, the issue went away. Disabling `vscode-rails` also disables the dependency `vscode-gemfile`, so it could be that the issue is with that extension instead. 

# System
- macOS 10.12.6
- VS Code 1.25.1

**Comment by bung87** [comment]
thanks for your reporting ,from what I understood from your description,the completion wrongly trigger whether it's `.` or `:` especially the line has both `.` and `:`,I can confirm this problem exist but due to mine poor english I can't confirm it is the problem you described,I package a new extension with patch see if it would reduce this problem

[rails-0.8.0.vsix.zip](https://github.com/bung87/vscode-rails/files/2237784/rails-0.8.0.vsix.zip)

**Comment by bryantbj** [comment]
Sorry for the delay! I'll take a look at this tomorrow. Thank you!
